### ISSUE TITLE
Segment Pool Sharing

### ISSUE THREAD

**Issue by JohannesDeml** [vis2k/kcp2k#18]
Currently, the segment pool is static and therefore used by all KCP instances. This is a problem when using multiple KCP clients (e.g. for benchmarking) within the same program concurrently.

From what I understand there are two solutions to the problem: 
1. Giving each KCP instance its own Segment Stack
2. Use `ConcurrentStack<Segment>` for the pool.

I went with version two for my benchmark test (see https://github.com/JohannesDeml/NetworkBenchmarkDotNet/commit/47ec6b5741949f8867f830d2e60fea36d4e60a5d), since it was an easy change. However, giving each kcp its own pool might be more performant.

Other than the segment pool, the library seems to work fine with a concurrent benchmark setup. Is it in the interest of the maintainers to support multiple KCP instances running at the same time? And if so, which version do you prefer. I think both versions are quite easy to implement and I could provide a PR for it.

**Comment by vis2k** [comment]
good point. checking..

**Comment by vis2k** [comment]
each Kcp.cs instance now has it's own pool:
<img width="683" alt="2021-05-28_16-14-37@2x" src="https://user-images.githubusercontent.com/16416509/119952702-e1a8be80-bfcf-11eb-8cfc-be8e010a664a.png">

no more static state.
thanks for pointing it out @JohannesDeml !
sorry for late reply.

**Comment by JohannesDeml** [comment]
Nice, looks like a clean solution :)

**Comment by vis2k** [comment]
live on master :)
