### ISSUE TITLE
Will there be a non-Unity version?

### ISSUE THREAD

**Issue by Fydar** [vis2k/kcp2k#3]
Will this project look at creating a version of this package designed for outside of Unity?

I see that [Telepathy](https://github.com/vis2k/Telepathy) does have projects for usage outside of Unity; and I wonder whether it's the explicit direction of kvp2k to be a Unity-only package.

**Comment by Vytek** [comment]
I think it is very important to have a server in NOT Unity application ;-) to create easily a client - server system MMO...

**Comment by shaw4** [comment]
Yea, having KCP outside of Unity as it's own standalone window would be great.

**Comment by vis2k** [comment]
sure, will be very easy to do. I'd say some time this month.

**Comment by vis2k** [comment]
done. latest version doesn't depend on UnityEngine anymore.
