### ISSUE TITLE
Kcp hangs on invalid networkAddress

### ISSUE THREAD

**Issue by MrGadget1024** [vis2k/kcp2k#31]
Any Mirror example with the HUD...type '123' into the address field and click Client.  Unity hangs.

Windows 10 / master

**Comment by vis2k** [comment]
we have test coverage for that already:
<img width="581" alt="2021-11-28_11-21-14@2x" src="https://user-images.githubusercontent.com/16416509/143764010-3a94671d-0cbc-457d-a360-378d7c2e5e8e.png">

might be kcp TRANSPORT for mirror related, will check later today

**Comment by vis2k** [comment]
can't reproduce.
feel free to reopen but I think this was fixed a while ago
