### ISSUE TITLE
Try to use golang to develop the server, but I can't receive the message

### ISSUE THREAD

**Issue by okitaAsuka** [vis2k/kcp2k#37]
go server library： https://github.com/xtaci/kcp-go

The udp connection can be connected, but the subsequent message sending server cannot receive it, and I have also tried to directly call the SendReliable method, but it is invalid.
I don’t know the reason why the message can’t enter the server, ask for help

thanks in advance

**Comment by Samicelus** [comment]
any news?

**Comment by 0990** [comment]
kcp2k is base on kcp, but not raw kcp, It can't direct communite with kcp-go,I implement one in golang,you can have a try: https://github.com/0990/kcp2k-go
