### ISSUE TITLE
original kcp

### ISSUE THREAD

**Issue by neshcodes** [vis2k/kcp2k#41]
i apply kcp2k old ver in unity, and use the netty kcp on server
but throw ex when i upgrade the kcp to 1.19
i found out the message add header
is there any way to fix the original kcp?

**Comment by sgf** [comment]
> Kcp.cs based on kcp.c v1.7

**Comment by sgf** [comment]
> i apply kcp2k old ver in unity, and use the netty kcp on server but throw ex when i upgrade the kcp to 1.19 i found out the message add header is there any way to fix the original kcp?

im,sorry,the last update to   [V1.19](https://github.com/vis2k/kcp2k/commit/56720b0b10dd752f5c33e5958fd6736147c85825)
you can reopen the issue
